### ISSUE TITLE
Sublime like snippets

### ISSUE THREAD

**Issue by lmajano** [ilich/vscode-coldfusion#26]
I love how in sublime cfml plugin we can do shortcuts to do insertions of constructs like this:

like this:

```
 // super+alt+d  <cfdump var="##">
    {
    "keys": ["shift+command+d"], "command": "insert_snippet",
    "args": { "contents": "<cfdump var=\"#${1:$SELECTION}#\" />" },
    "context":
	    [
	        {"key": "selector", "operator": "equal", "operand": "embedding.cfml"},
      {"key": "selector", "operator": "not_equal", "operand": "source.cfml.script"}
	    ]
	},
```

Is this possible? I know you can have snippets, but shortcuts for insertions would be cool

**Comment by ilich** [comment]
It seems to be doable: https://manual.macromates.com/en/snippets

Sublime supports TextMate snippets, doesn't it?

**Comment by lmajano** [comment]
I am not familiar with TextMate, but sure :)

**Comment by KamasamaK** [comment]
Are you asking about [keybindings to snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets)?

If so, one for `cfdump` would just require the following added to your `keybindings.json`:
```json
{
    "key": "shift+ctrl+d",
    "mac": "shift+cmd+d",
    "command": "editor.action.insertSnippet",
    "when": "editorLangId == lang-cfml && editorTextFocus",
    "args": {
        "langId": "lang-cfml",
        "name": "cfdump"
  }
}
```

In this case, the context is based on language ID, which is the same for tag and script syntaxes, instead of a syntax scope selector. The rest of the linked page contains everything documented about snippets in VS Code.

**Comment by lmajano** [comment]
Wow, yes that worked.  However the `mac` command didn't work in mac. I had to use the `key` instead.  I will close this ticket, since I can see this more of a user thing and not core.

**Comment by lmajano** [comment]
Ok, let me reopen with one more addition. How do you distinguish if you are in `cfscript` mode or in `tag` mode?  As the snippets need to change depending on context.  Is this available?

**Comment by KamasamaK** [comment]
I added the `mac` part because I've seen it used in keybindings for extensions, but I don't have OSX to test. It might not work for user keybindings at all or perhaps I misunderstood how it is supposed to work.

Regarding script or tag, again the context is the language ID which is the same for both. This has been discussed in other issues already, but having separate language IDs would solve this and some other issues surrounding the differences.

**Comment by lmajano** [comment]
I would vote for having two different language IDs as you can do certain things in script that you can't in tags and vice versa

**Comment by ilich** [comment]
If we have proper CFML parser then it should work for one language ID, I think. The first thing I want to do for the next version is to update TextMate syntax script to understand CFML, cfscript, CFML components, HTML and SQL contexts. As I understood this is the approach used for PHP plugin, for example.

Current TextMate syntax is few years old and should be updated.

I also did research if it is possible to provide highlighting via language server. Unfortunately it doesn't seem to be doable, because of VS Code performance implications.

**Comment by ilich** [comment]
Do you think we should have language ID & snippets for CFC's and CFM's?

**Comment by lmajano** [comment]
Yes, definitely.  Each context should have its own snippets. But yes, you need the language ID differentiated.  Also remember that you can do code islands in CFML as well, basically having in a cfm or tag based file the `cfscript` tags. Which would be difficult as well.

The Java plugin using a Java binary for the language server, which we can easily do with commandbox as well as it works the same way.

**Comment by KamasamaK** [comment]
You _could_ have the extension dynamically change various things based on context within the same language ID, which a proper parser could facilitate, but I don't think that is the best solution. I think dynamically changing the **language ID** in those cases would be ideal, and the associated settings for that language ID would simply be used in those contexts. Settings such as comments (see #18) would be simple with separate (and dynamic) language IDs instead of having to explicitly address the differences in code.

In the case of static items like user snippets and user keybindings, you can only reasonably base them off of language ID as there is no access to a more specific context.

**Comment by lmajano** [comment]
agreed!  Exciting!!!

**Comment by lmajano** [comment]
Ok, will close this now.
