### ISSUE TITLE
Generate closing tag

### ISSUE THREAD

**Issue by bardware** [ilich/vscode-coldfusion#40]
Hi,

I worked on some code over the past days and uses code as editor. I noticed that very often I took an `<cfif` tag and copied it to another line in the code. Then I needed a closing tag and have no idea how to get it other than writing it myself. In cfeclipse I go to the end of the opening tag and position the cursor right in front of the `>` symbol. When I now press `>` a closing tag is generated which I can cut and paste at the position where I need it.
Does your plugin provide a similar functionality?

**Comment by ericyd** [comment]
I assume you're describing functionality similar to the way `html` files will auto-close tags when the tag is completed, something like this?
![div-auto-close](https://user-images.githubusercontent.com/8379268/37785772-405c6cfe-2db8-11e8-88e0-bff3f464768c.gif)

If that's what you're trying to achieve, unfortunately this plugin will not do it. My understanding is that this would require a language server instead of just the snippets that this plugin provides. The proposal to add a language server to this plugin has been [discussed in depth](https://github.com/ilich/vscode-coldfusion/issues/11) but as far as I know there is no real development being done on it.

**Comment by bardware** [comment]
OK, thanks for the reply. I had no idea it might be complicated. Thanks for the pointer to the discussion regarding the language server.
